file_length:
    warning: 600
    error: 800
 
force_unwrapping:
    warning: 40
    error: 60
    
implicity_unwrapped_optional:
    mode: all
    severity: error
    
included:
    - Movie&Serie/
 
excluded:
    - Pods
    - Pods/

disabled_rules:
 - trailing_whitespace
 - identifier_name
